/* Generated By:JavaCC: Do not edit this line. huracanesCompiladorConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface huracanesCompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IdHuracan = 1;
  /** RegularExpression Id. */
  int NombreHuracan = 2;
  /** RegularExpression Id. */
  int VelocidadHuracan = 3;
  /** RegularExpression Id. */
  int Fecha = 4;
  /** RegularExpression Id. */
  int Latitud = 5;
  /** RegularExpression Id. */
  int Longitud = 6;
  /** RegularExpression Id. */
  int Vientos = 7;
  /** RegularExpression Id. */
  int DIA = 8;
  /** RegularExpression Id. */
  int MES = 9;
  /** RegularExpression Id. */
  int ANIO = 10;
  /** RegularExpression Id. */
  int NUMERODOSDIGITOS = 11;
  /** RegularExpression Id. */
  int HORA = 12;
  /** RegularExpression Id. */
  int VIENTOS = 13;
  /** RegularExpression Id. */
  int SIGNOMENOS = 14;
  /** RegularExpression Id. */
  int COMA = 15;
  /** RegularExpression Id. */
  int LETRAS = 16;
  /** RegularExpression Id. */
  int PUNTO = 17;
  /** RegularExpression Id. */
  int NUMERO = 18;
  /** RegularExpression Id. */
  int NUMEROFILAS = 19;
  /** RegularExpression Id. */
  int NUMEROCOMA = 20;
  /** RegularExpression Id. */
  int ESPACIO = 21;
  /** RegularExpression Id. */
  int REGION = 22;
  /** RegularExpression Id. */
  int LAT = 23;
  /** RegularExpression Id. */
  int LON = 24;
  /** RegularExpression Id. */
  int RECID = 25;
  /** RegularExpression Id. */
  int ESTADOSISTEMA = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IdHuracan>",
    "<NombreHuracan>",
    "<VelocidadHuracan>",
    "<Fecha>",
    "<Latitud>",
    "<Longitud>",
    "<Vientos>",
    "<DIA>",
    "<MES>",
    "<ANIO>",
    "<NUMERODOSDIGITOS>",
    "<HORA>",
    "<VIENTOS>",
    "<SIGNOMENOS>",
    "\",\"",
    "<LETRAS>",
    "\".\"",
    "<NUMERO>",
    "<NUMEROFILAS>",
    "<NUMEROCOMA>",
    "<ESPACIO>",
    "<REGION>",
    "<LAT>",
    "<LON>",
    "<RECID>",
    "<ESTADOSISTEMA>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\" \"",
  };

}
